stages:
  - build

variables:
  KNT_ORIGINAL_PROJECT_PATH: "konnect/dxf-parser"
  KNT_BUILD_GIT_REPO: "no_git"
  KNT_BUILDER_TOOLS : "@konnect/builder-tools@^2000"
  KNT_PATH_BUILDER_TOOLS: "./.dglobal/lib/node_modules/@konnect/builder-tools"

build_branch:
  stage: build
  script:
  # On récupère les scripts de build
  - npm install --prefix $CI_PROJECT_DIR/.dglobal/ $KNT_BUILDER_TOOLS -g
  # Mise en place des versions dans le package.json
  - (node $KNT_PATH_BUILDER_TOOLS/tasks/common/prepare-build-client.js) || exit 1;
  # Récupération du nom du projet
  - export KNT_PACKAGE_NAME=$(node $KNT_PATH_BUILDER_TOOLS/tasks/common/get-project-name)
  # Compilation
  - npm install
  - npm run compile
  # Push to NPM @konnect/sequelize
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/push-to-gogit.sh $KNT_BUILD_GIT_REPO $CI_COMMIT_REF_NAME $KNT_ORIGINAL_PROJECT_PATH $KNT_PACKAGE_NAME
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/clean-tmp.sh
