stages:
  - build
  - extra

variables:
  KNT_ORIGINAL_PROJECT_PATH: "konnect/dxf-builder"
  KNT_BUILD_GIT_REPO: "no_git"
  KNT_BUILDER_TOOLS : "@konnect/builder-tools@^2000"
  KNT_PATH_BUILDER_TOOLS: "./.dglobal/lib/node_modules/@konnect/builder-tools"

build_branch:
  stage: build
  tags:
    - linux
  script:
  # On récupère les scripts de build
  - npm install --prefix $CI_PROJECT_DIR/.dglobal/ $KNT_BUILDER_TOOLS -g
  # Builds & tests & deploy
  - (cd $KNT_PATH_BUILDER_TOOLS && npm run build-n-deploy-server $CI_PROJECT_DIR $KNT_ORIGINAL_PROJECT_PATH $KNT_BUILD_GIT_REPO) || exit 1;
